import streamlit as st

from .data_loader import load_recommendations
from .helpers import page_header, section_header, kpi_card, empty_state


def render_recommendations():
    page_header(
        "Recommendation Engine",
        "Customer-product recommendations generated by the personalization engine.",
    )

    df = load_recommendations()
    if df.empty:
        empty_state("Recommendation data is not available.")
        return

    total = len(df)
    customers = df["customer_id"].nunique() if "customer_id" in df.columns else 0
    products = df["product_name"].nunique() if "product_name" in df.columns else 0

    c1, c2, c3 = st.columns(3)
    with c1: kpi_card("Recommendations", f"{total:,}")
    with c2: kpi_card("Customers", f"{customers:,}")
    with c3: kpi_card("Products", f"{products:,}")

    section_header("Explore Recommendations")
    c1, c2 = st.columns(2)

    with c1:
        customer = "All"
        if "customer_id" in df.columns:
            customer = st.selectbox(
                "Customer",
                ["All"] + sorted(df["customer_id"].dropna().astype(str).unique().tolist()),
            )

    with c2:
        product = "All"
        if "product_name" in df.columns:
            product = st.selectbox(
                "Product",
                ["All"] + sorted(df["product_name"].dropna().astype(str).unique().tolist()),
            )

    filtered = df.copy()
    if customer != "All":
        filtered = filtered[filtered["customer_id"].astype(str) == customer]
    if product != "All":
        filtered = filtered[filtered["product_name"].astype(str) == product]

    display_columns = [
        c for c in [
            "customer_id", "product_name", "recommendation_score",
            "recommendation_confidence", "recommendation_reason",
            "campaign_objective",
        ] if c in filtered.columns
    ]
    st.dataframe(filtered[display_columns], use_container_width=True, hide_index=True)

    if "product_name" in df.columns:
        section_header("Recommended Product Distribution")
        st.bar_chart(df["product_name"].value_counts())
